### PR TITLE
Combine two VMWare guides into one: vmw-player.

### LINKED ISSUE #949: Consolidate, combine vmware guides into one.
**Describe the error/improvement to an existing document or image**
Currently, three VMware guides exist with overlapping sections. For example, each shows how to create a VM instance with VMware Workstation Player. As part of effort to improve user workflows, working with @odwdinc, I suggest we: 
* consolidate 2-3 of these guides into one while explaining options with sphinx-tabs
* Revise screenshots for CL VMware preconfigured image to reflect VWware 15. 
* Move all screenshots into `_figures` global location

- https://docs.01.org/clearlinux/latest/get-started/virtual-machine-install/vmw-player.html
- https://docs.01.org/clearlinux/latest/get-started/virtual-machine-install/vmw-player-preconf.html
- https://docs.01.org/clearlinux/latest/get-started/virtual-machine-install/vmware-esxi-install-cl.html

### PR DESCRIPTION
**Pull request by mvincerx**
Closes #949

### CODE REVIEW

**Comment by mvincerx** [comment]
@odwdinc.  Please see my latest commit per our last meeting. Hoping to merge this today. Thanks

**Comment by mvincerx** [comment]
@odwdinc.  Will you please review/approve this PR?

**Comment by odwdinc** [comment]
looks good

**Comment by mvincerx** [comment]
Re-opening this so that I can merge.

**Pull request merged**
