### PR TITLE
nvidia.rst: Add a section on GCC compatibility

### PR DESCRIPTION
**Pull request by lebensterben**
Address the issue mentioned in https://github.com/clearlinux/distribution/issues/1835

This commit helps the user to detect a potential problem early, and provides a workaround.

### CODE REVIEW

**Comment by puneetse** [comment]
Thanks for writing this up. I'm thinking adding this content to the tutorial is going to be distracting because it is duplicating functionality/information of the nvidia-installer. From the CL side this mismatch should not be happening and the nvidia-installer does the check, blocks accordingly, and provides the same info. So I feel having users do the check manually is redundant.

**Comment by lebensterben** [comment]
Indeed the check is redundant. 

But without this, users would spend quite some time applying workarounds and making modifications to their system, and only to find out the GCC version mismatch when they install the driver. Then they may spend the same amount of time restoring their system back to default.

This check avoids this kind of situation and improves user experience.

**Comment by puneetse** [comment]
Let's leave this out of the documentation for the time being since it should not be happening in the first place. I do think it's helpful that you put it in your scripts. If this become a recurring problem, we can look at resurrecting this PR.

**Comment by mvincerx** [comment]
@lebensterben, you could also publish these steps on [the forum](https://community.clearlinux.org/). 
BTW: These are super nice regex captures.

**Pull request closed without merging**
