### PR TITLE
Upgrades to Jinja2 2.10.1, dependency for bundle_lister.py.

### PR DESCRIPTION
**Pull request by mvincerx**
Signed-off-by: Michael Vincerra <michael.vincerra@intel.com>

### CODE REVIEW

**Comment by mvincerx** [comment]
Hey @intelkevinputnam, can you please ensure build environment has the lastest Jinja2, using this:
`pip install Jinja2==2.10.1`. This PR formally updates the the Jinja2 dependency.

**Comment by intelkevinputnam** [comment]
@mvincerx Travis appears to be having some network issues, which is the root cause of the build failure. I went ahead and merged it, and everything looks good.

**Comment by mvincerx** [comment]
That's good news. I was  trying to solve the network timeout issues--still haven't found the answer. Anyway, error was not related to the code/requirements.

**Comment by intelkevinputnam** [comment]
Nothing we can do to solve it. It is on their side and is impacting other projects as well.

**Pull request merged**
