### PR TITLE
Edited for grammar, formatting, and text flow.

### PR DESCRIPTION
**Pull request by MCamp859**
Deleted prompt character. Replaced # with sudo.
Assigned bash role to code blocks with user entries.
Edited text for active voice and consistency between steps.

Signed-off-by: MCamp859 <mary.camp@ptiglobal.net>

### CODE REVIEW

**Comment by MCamp859** [comment]
@nesiusra Please assign an engineer from your team to do a technical review of this content, thanks.

**Comment by nesiusra** [comment]
@ahkok - could you please review this one?  Thx!

**Comment by ahkok** [comment]
So this all looks OK. The use of `sudo` is definitely good, but I really do not like it at this scale, because the amount of commands that require it is so large it is becoming distracting.

I would rather see a general remark near the top that people need to have root permissions for all the commands in this guide, and therefore should prepend `sudo` or just use `sudo su -` once from the start.

Given the amount of commands and here documents, this is probably too complex and novice users will likely fail to properly execute the here document sections properly. We should consider creating shell scripts and shipping them in CLR or use indirect ways of describing what needs to be done, for instance we can say "create a file `/foo/bar` with the following content: <quote content>".

Other than that, this is fine, I don't see any technical issues with these changes.

**Comment by rcaballeromx** [comment]
@ahkok Thank you very much for taking the time to review this content. I agree with you on the complexity and amount of commands. I concur that scripting some of the steps would be a great help and I will raise the issue with the documentation team. We are adding the sudo commands to enable document based testing. I am meeting with the QA team to see what alternatives we can use, including your recommendations. 
For the time being, I suggest merging @MCamp859's edits and we will revisit the use of sudo once we have reached a new agreement with QA. Is this acceptable @ahkok?

**Comment by ahkok** [comment]
yes, I we can merge this.

**Pull request merged**
