### PR TITLE
Added stacks section to guides.rst, migrated tutorials, and revised w…

### LINKED ISSUE #579: Reorg: Moves Stacks tutorials to new Stacks section in guides.rst
**Describe the error/improvement to an existing document or image**
1. Add a new Stacks section in guides.rst
https://clearlinux.org/documentation/clear-linux/guides

2. Migrate all tutorials from here, https://clearlinux.org/documentation/clear-linux/tutorials, to the above guides location. 

3. Revise word usage from tutorial to guides in all stacks-related tutorials. 

**Additional context**

### PR DESCRIPTION
**Pull request by crsawyer314**
…ord usage.

closes #579

Signed-off-by: Catherine Sawyer <crsawyer314@gmail.com>

### CODE REVIEW

**Comment by mvincerx** [comment]
This looks great, @crsawyer314. Like I mentioned, we need feedback from @bd-dean, when she returns on 8 July. Please hold on this until then.

**Comment by bd-dean** [comment]
Can I request one more change before merging:  in the AWS Greengrass guide, please add "computer-vision-models" to the required bundles list (at about line 99).

**Comment by crsawyer314** [comment]
Will do. I'll probably make these changes in the morning.

**Comment by mvincerx** [comment]
@bd-dean. Hey, stay on vacation! jk. Thanks for reviewing. Yes, @crsawyer314 go ahead with more edits. 
FYI I'm holding fire on this until some website build issues are resolved. More commits are good in the meantime.

**Comment by ttzeng** [comment]
> Can I request one more change before merging: in the AWS Greengrass guide, please add "computer-vision-models" to the required bundles list (at about line 99).

The `computer-vision-models` bundle will be installed while installing the `computer-vision-basic` bundle, so the current list should be fine, IMHO.

**Comment by mvincerx** [comment]
@crsawyer314. I'll help you resolve these conflicts; they're the result of merging GH-596, with the terms of use.  Please wait for me to help you with this before making any more commits.

**Comment by mvincerx** [comment]
@crsawyer314 Just for the record, I'll wait until @bd-dean brings another PR that needs to precede this. Stay tuned--like we discussed today. :)

**Comment by mvincerx** [comment]
@bd-dean Waiting on new PR.

**Comment by mvincerx** [comment]
@crsawyer314 I welcome any other PRs you may want to contribute. 
Closing this PR to allow for GH-644 to handle reorg of stacks.  This PRs content is too far out of date.

**Pull request closed without merging**
