### PR TITLE
Added recommendation to run LTS kernel for proprietary NVIDIA drivers…

### PR DESCRIPTION
**Pull request by eeeple**
… (see https://github.com/clearlinux/distribution/issues/1725)

### CODE REVIEW

**Comment by puneetse** [comment]
See also https://github.com/clearlinux/clear-linux-documentation/issues/918

I'm hesitant to add this as a blanket recommendation because these tend to be point-in-time issues and on the other hand I have seen long-since solved issues trying to use LTS kernels. So, I think the recommendation should stay loose or at most recommend trying a *different* kernel variant. 

There is this sentence further below in the document that gets inherited from the DKMS section: `The Long Term Support (LTS) kernel variant is more likely to remain compatible between updates with NVIDIA drivers.` which could be moved up into the Known issues section instead.

**Comment by eeeple** [comment]
@puneetse Thanks for the input ! I've removed the previous paragraph and rephrased with something more in line with the remark in the dkms section.

**Comment by mvincerx** [comment]
I'm fine with the latest push. @eeeple Replace this PR with a branch, instead of submitting a PR on your `master` branch. After @puneetse approves, [create a branch as on a standard Git workflow](https://docs.01.org/clearlinux/latest/collaboration/collaboration.html#contribute-via-github), and submit a new PR with the approved change,

**Comment by mvincerx** [comment]
@eeeple. I'd like to give you credit for this, but you need to submit a PR with a new branch in order for this to be accepted. Please indicate if you want to do so by Thurs. 02-20-2020. Otherwise, I'll close this PR and we'll make a new one with your edit.

**Comment by eeeple** [comment]
@mvincerx I'm sorry, didn't have the time to push before. Submitted as #1034 from new branch. Thank you 😄

**Pull request closed without merging**
