### PR TITLE
Improvements to link checking

### PR DESCRIPTION
**Pull request by intelkevinputnam**
Changes to Makefile:

Added line to linkcheck recipe to run "parse-link-check.py"
Appended "-" to linkcheck launch so it continues after returning errors (broken links cause this)
File added:

parse-link-check.py generates broken_links.html in source/_build/linkcheck with live hyperlinks for manually checking broken links - in many cases the URLs are correct but break as the request was not made from a browser - need to be manually checked to verify they aren't broken

### CODE REVIEW

**Comment by intelkevinputnam** [comment]
Will add documentation to parse-link-check.py in next push

**Comment by intelkevinputnam** [comment]
@mvincerx Should be all set now.

**Comment by mvincerx** [comment]
@intelkevinputnam. `parse-link-check.py` worked fine for me this time.  0 unmatched broken links. 
I recommend a small change in the directory structure to simplify organization of python scripts. 
Change `source/scripts/_python/parse-link-check.py` to `source/scripts/_python/linkcheck/parse-link-check.py`. Name the directory whatever you choose. Of course, you'll have to edit the Makefile too. 

I'll have to make the same change with my python script in GH-349. The main reason for this is that `requirements.txt`, and other files specific to the `.py.` script will be less likely in conflict.

**Comment by mvincerx** [comment]
@intelkevinputnam. Like we discussed, no need for separate directory. LMK when you've finished commits.

**Comment by intelkevinputnam** [comment]
@mvincerx Should be done with commits. Just to be clear, we're leaving the directory structure as is, right?

**Comment by mvincerx** [comment]
Hey @intelkevinputnam.  Yes, for now, let's leave the directory structure as is. There aren't any conflicts; it could just be messy and potentially confusing (e.g., requirements.txt) for other developers. So for Q1 2019, let's both create a ticket to subdivide the directory with our different scripts. Does that work for you?

**Comment by intelkevinputnam** [comment]
@mvincerx moved to subdirectory

**Comment by mvincerx** [comment]
LGTM. 👍

**Pull request merged**
