### PR TITLE
Moves content from bare-metal-install-beta to bare-metal-install

### PR DESCRIPTION
**Pull request by mvincerx**
- Revises bare-metal-install-beta intro and uses an `include` to bare-metal-install
- Removes bare-metal-manual-install; content now included in bare-metal-install
- Reorganizes all images; adds two new images, Figs 1-2 in bare-metal-install.

Signed-off-by: Michael Vincerra <michael.vincerra@intel.com>

### CODE REVIEW

**Comment by mdhorn** [comment]
@mvincerx Not what you want to hear, but this may need to be on hold for a bit.
Following the directions, the image that I downloaded still has the old ister_gui.py installer.
Need to follow up with DevOps when they will switch to the new images using clr-installer. I thought we had closed on this before the holiday.

**Comment by mvincerx** [comment]
@intelkevinputnam. Hold per Engineering.  Also, I'm troubleshooting build errors. Will ask for review later. 
@mdhorn. No problem. Please keep me posted. 
Major issue solved: Live desktop beta installer now has disk encryption. 
https://clearlinux.org/documentation/clear-linux/get-started/bare-metal-install-beta#bare-metal-install-beta

**Comment by mvincerx** [comment]
Feel free to follow up with a PR for BKMs, like we discussed. Going forward, please hold off on reviewing unless I request it.  I halted work on this PR 3 weeks ago--but will resume this week.

**Comment by mvincerx** [comment]
FYI: Hold all reviews, please.

**Pull request closed without merging**
