### PR TITLE
Adds reference in bare-metal-install-* to use YAML config file to install

### LINKED ISSUE #1083: Add cross-reference in bare-metal-install-desktop to install-configfile
**Describe the error/improvement to an existing document or image**

Add a cross-reference for sysadmin to address how to find using a yaml file for multi-install. 

From:
- https://docs.01.org/clearlinux/latest/get-started/bare-metal-install-desktop.html
- https://docs.01.org/clearlinux/latest/get-started/bare-metal-install-server.html

To:
https://docs.01.org/clearlinux/latest/get-started/install-configfile.html

**Screenshots**
NA

**Environment (please complete the following):**
NA

**Additional context**
NA

### PR DESCRIPTION
**Pull request by mvincerx**
- Improve discoverability of install-configfile
- Closes #1083

Signed-off-by: Michael Vincerra <michael.vincerra@intel.com>

### CODE REVIEW

**Comment by mvincerx** [comment]
@bktan8 or @mdhorn, I'd like either one of you to approve this. Whoever gets here first... 😉

**Comment by mvincerx** [comment]
> Maybe is Bun is more clear on this one, but I'm not sure of the goal here.
> 
> * Using the interactive installer ISO with a custom YAML config?
This, above, is the goal.

**Comment by bktan8** [comment]
@mvincerx - I think it would be better to provide this as an "alternative" option as part of the intro.  Sticking it between the "Preliminary" and "Install from live image" seems out of place.  Something like "Alternative: Unattended installation using a configuration file, see :ref:`install-configfile`."

**Comment by bktan8** [comment]
Also add it as a "Related topic" at the bottom.

**Comment by mvincerx** [comment]
@bktan8.  I like your suggestions. Please take a look and LMK. Thanks.

**Pull request merged**
