### PR TITLE
Update to parse-link-check.py

### PR DESCRIPTION
**Pull request by intelkevinputnam**
Updated parse-link-check.py script to ignore anchors. 

Motivation:

1. Anchors in .rst files in GitHub are considered broken by the tester though they resolve correctly when manually clicking through on the browser.
2. Broken anchors should not block the site from being built.
3. There are now 3 categories in broken_links.html
   1. unmatched broken links
   2. broken links on the white list
   3. broken anchors

### CODE REVIEW

**Comment by mvincerx** [comment]
What do you use as your input file, as argument, for testing?

**Comment by mvincerx** [comment]
Let's go over this PR on Monday when we're both in the office. When I run `make link`, I notice several build errors, but it's difficult to distinguish between those errors that you wish to raise vs. those that could be legitimate build errors.   

Maybe this can be helped by revising the embedded documentation in the .py file. Let's discuss.

**Comment by intelkevinputnam** [comment]
@mvincerx Please review again.

**Comment by mvincerx** [comment]
LGTM. Thanks for improving documentation of your code.

**Pull request merged**
