### PR TITLE
Applies grammatical and trademark edits:

### PR DESCRIPTION
**Pull request by mvincerx**
- Linux kernels are updated per clr/bundles active status
- Fulfills JIRA CLEAR 3107
Signed-off-by: Michael Vincerra <michaelx.vincerra@intel.com>

### CODE REVIEW

**Comment by mvincerx** [comment]
Pending feedback also from Miguel Bernal.

**Comment by miguelinux** [comment]
LGTM

**Comment by miguelinux** [comment]
It is ok to merge

**Comment by mvincerx** [comment]
@miguelinux FYI: I had to remove one broken hyperlink. Otherwise, no other changes after we talked this morning. I will merge. Saludos.

**Pull request merged**
