### PR TITLE
Add memcached instructions for v2.0

### PR DESCRIPTION
**Pull request by bd-dean**
Preparing for v2.0 release

### CODE REVIEW

**Comment by intelkevinputnam** [comment]
@bd-dean Just need to define the link for the label: :ref:`Hardware Configuration`

**Comment by intelkevinputnam** [comment]
@bd-dean the best way to fix this is to add a label `.. _dbrs-hardware-configuration` above the header "Hardware Configuration". Then change the ref to use `dbrs-hardware-configuration`.

**Comment by bd-dean** [comment]
> @bd-dean the best way to fix this is to add a label `.. _dbrs-hardware-configuration` above the header "Hardware Configuration". Then change the ref to use `dbrs-hardware-configuration`.

Thank you!  This worked and build is successful. I also sorted out the build issues on my local system (python3 path...) so it's building there again too.

**Comment by bd-dean** [comment]
@intelkevinputnam thanks!  This worked, it's also building on my local system (was a python3 path issue, surprise!)

**Comment by bd-dean** [comment]
@mvincerx  this is ready to go.

**Pull request merged**
