### PR TITLE
Update links to FaaS source to point to version 1.0

### PR DESCRIPTION
**Pull request by bd-dean**

### CODE REVIEW

**Comment by phmccarty** [comment]
@bd-dean Can you add some details to the commit about why the FaaS repo being is locked to v1.0? Is it because the latest version breaks compatibility?

**Comment by bd-dean** [comment]
> @bd-dean Can you add some details to the commit about why the FaaS repo being is locked to v1.0? Is it because the latest version breaks compatibility?

Exactly that reason.  From the request: "... v2.0 of FaaS, which is NOT compatible with OpenVINO R3 released with Clear Linux’s computer-vision-basic bundle."

**Comment by phmccarty** [comment]
@bd-dean Okay, thank you! Looks good to me.

**Comment by mvincerx** [comment]
Built, tested, passed. Thank you both for staying on top of this document. Merging.

**Pull request merged**
