### PR TITLE
guides: Add new Kubernetes migration guide

### PR DESCRIPTION
**Pull request by mdhorn**
This guide provides direction in upgrade Kubernetes from 1.17.x release up to 1.19.x release due to Clear missing the 1.18.x release.

### CODE REVIEW

**Comment by mvincerx** [comment]
hey @mdhorn. Will you please provide the actual URLs for these refs in the doc?
* kubernetes container orchestration system
* cloud-native-setup
* understanding basic kubernetes architecture
* deploying an application to your cluster
* pod network add-on
* joining your nodes

Once you provide these, I will fix the URLs refs.
After this, you can rebase and resolve conflict with `copyright` in the conf.py.

**Comment by mdhorn** [comment]
@mvincerx Thanks. I'll have to go chase those down and they came from one of the other tutorials I borrowed as a template. A quick scan of the built htmlall I see a few other formatting changes I need to fix too.

**Comment by mvincerx** [comment]
I fixed all errors except the hyperlinks, which you need to provide.  Otherwise, don't worry about any other errors.

**Comment by mdhorn** [comment]
@mvincerx  Let me know if you want me to squash commits.

**Comment by mvincerx** [comment]
Can you schedule a call for us to discuss sometime Thurs. afternoon? Thanks.

**Comment by mdhorn** [comment]
@mvincerx I cleaned up the commits. The build is working on my system and seems CI is passing.
Ready for review.

**Comment by mvincerx** [comment]
LGTM. Thanks for squashing.

**Pull request merged**
