### PR TITLE
Update URLs to use CDN and fix documentation build warning

### PR DESCRIPTION
**Pull request by gvancuts**
There are two commits in this PR:
1. Fix a documentation build warning (see below [1])
2. Update the URLs pointing at https://download.clearlinux.org to use the CDN (i.e. https://cdn.download.clearlinux.org). This will greatly improves the user experience of those not in the US.

[1] Documentation build warning:
```
$ make html
make -C source html
make[1]: Entering directory '/home/gvancuts/work/clear-linux-documentation/source'
sphinx-build -b html -d _build/doctrees   . _build/html
Running Sphinx v1.7.5
loading pickled environment... done
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 1 source files that are out of date
updating environment: 0 added, 1 changed, 0 removed
reading sources... [100%] clear-linux/reference/reference                                                                                                                                                          
/home/gvancuts/work/clear-linux-documentation/source/clear-linux/reference/reference.rst:9: WARNING: toctree contains reference to nonexisting document 'clear-linux/reference/openssh-server'
looking for now-outdated files... none found
pickling environment... done
checking consistency... /home/gvancuts/work/clear-linux-documentation/source/clear-linux/reference/bundles/openssh-server.rst: WARNING: document isn't included in any toctree
done
preparing documents... done
writing output... [100%] sitemap                                                                                                                                                                                   
generating indices... genindex
writing additional pages... search
copying static files... done
copying extra files... done
dumping search index in English (code: en) ... done
dumping object inventory... done
build succeeded, 2 warnings.

The HTML pages are in _build/html.

Build finished. The HTML pages are in _build/html.
make[1]: Leaving directory '/home/gvancuts/work/clear-linux-documentation/source'
```

### CODE REVIEW

**Comment by mvincerx** [comment]
@gvancuts. Thank you for the PR. Yes, CDNs will likely be faster. Overall, these work well, just need internal review. Also, please rebase this branch on upstream master; build errors were already resolved. 

@gtkramer or @phmccarty, can you confirm that using `cdn`   in `https://cdn.download[...]` will work OK from DevOps perspective?

**Comment by gvancuts** [comment]
> @gvancuts. Thank you for the PR. Yes, CDNs will likely be faster. Overall, these work well, just need internal review. Also, please rebase this branch on upstream master; build errors were already resolved.

I have removed the commit that's already in master, rebased my branch and force-pushed it. Thanks

**Comment by mvincerx** [comment]
Hi @gvancuts. Your last commit looks good. CL DevOps, @gtkramer, confirms your addition of `cdn`. 
Would you please create a branch (from this content) and submit that new branch as a PR? 
I can't accept PRs directly on `master`.  Just in case, here's [how to create a branch from your existing branch](https://sebastian.expert/git-create-new-branch-from-existing-branch/) `master`.

**Comment by gvancuts** [comment]
> Would you please create a branch (from this content) and submit that new branch as a PR?
> I can't accept PRs directly on `master`. Just in case, here's [how to create a branch from your existing branch](https://sebastian.expert/git-create-new-branch-from-existing-branch/) `master`.

Sorry, I'm not following you. Are you saying that I need to push my tree to a new branch on this repo?

**Comment by mvincerx** [comment]
I'm requesting that you create a new branch to capture all proposed changes in this PR. (After you've done so, I will close this PR.) Given that you already committed directly to your master, I give an example on how to capture your existing changes on this PR and push them to a new branch.  
In the CLI, you can run: `git checkout -b {NEW_branch_name} master`.  Then, while you're on {NEW_branch_name}, you can run: `git push origin {NEW_branch_name}`. That should fix this issue.

**Comment by gvancuts** [comment]
OK, now I understand what you are asking, but I don't understand what issue it solves? Are you saying that you cannot merge this PR because the branch name in my fork is called `master` and not something else?!?

**Comment by mvincerx** [comment]
Please see my email. Also see "Contribute via GitHub" here: 
https://clearlinux.org/documentation/clear-linux/reference/collaboration.  Thank you.

**Comment by gvancuts** [comment]
New PR at #434 , closing this one.

**Pull request closed without merging**
