### PR TITLE
Updates to "Create a Clear Linux* based web server" tutorial (resolves issue #256). 

### PR DESCRIPTION
**Pull request by krisdale**
- Applied requested changes from Issue #256 
- Verified changes/full tutorial
- Minor grammatical/text edits for clarity.

Signed-off-by: Kristal Dale <kristal.dale@intel.com>

### CODE REVIEW

**Comment by krisdale** [comment]
I would like to add @odwdinc as reviewer, as the changes were originally requested by @odwdinc.

**Comment by mvincerx** [comment]
Invitation sent to @odwdinc to join as collaborator.

**Comment by krisdale** [comment]
@mvincerx  Backticks removed :)

**Comment by mvincerx** [comment]
LGTM.

**Pull request merged**
