### PR TITLE
Updated time.rst

### PR DESCRIPTION
**Pull request by eadamsintel**
When I tried this I had an error when I tried to set ntp to true that polkit was missing. Adding that bundle allowed the step to complete.

### CODE REVIEW

**Comment by puneetse** [comment]
Did you run the systemctl command with `sudo` when you got the polkit error? If I remember correctly, the polkit message is a symptom of invoking without having sudo permission first.

I'd be inclined not to document it this way because I don't think polkit is actually a timedatectl/ntp dependency.

**Comment by eadamsintel** [comment]
Good point. Using `polkit` is probably not the best way to do this.  The instructions don't indicate to use sudo so this is what happened.

```
$ timedatectl set-ntp true
Failed to set ntp: Unit polkit.service not found.
$ sudo timedatectl set-ntp true
```

Behind the corporate proxy I had issues getting the time to sync even once.

**Comment by puneetse** [comment]
Ah, so we should add`sudo` to the `timedatectl` command in the document and add direct to add polkit I think.

**Comment by eadamsintel** [comment]
I am ok with that. I did a pull request from the web interface so I am not sure the easiest way to modify it is.

**Comment by puneetse** [comment]
You can go back to the file in your branch : https://github.com/clearlinux/clear-linux-documentation/blob/eadamsintel-patch-1/source/guides/network/time.rst

and just hit the pencil icon to edit again

**Comment by mvincerx** [comment]
In case you're also using the CLI, don't forget to run `git pull [--rebase] upstream master` after.

**Comment by mvincerx** [comment]
👍 to @puneetse 's comment above re `sudo` and no need for `polkit` in this case. When I removed polkit, CL still allowed me to set the timezone. @eadamsintel LMK if you need any help on the PR.

**Comment by mvincerx** [comment]
LGTM. Thanks, @eadamsintel.

**Pull request merged**
