### PR TITLE
Add reDocs GUI support

### PR DESCRIPTION
**Pull request by intelkevinputnam**
Update to repo to support using reDocs GUI build of docs without configuration after pulling the repo.

### CODE REVIEW

**Comment by intelkevinputnam** [comment]
1. Added .tox and MANIFEST to .gitignore
2. Added py rule to make.bat to enable building of bundles.html.txt in Windows
3. Added .tox to exclude_patterns in conf.py
4. Added tox.ini and setup.py support files to project.

**Comment by intelkevinputnam** [comment]
I snuck a fix into manpages.py for Windows only, which was caused by not opening a file in UTF-8 encoding and run into a UTF-8 encoded character. This problem did not impact the Linux build. Both Windows and Linux build of docs should now work.

**Comment by mvincerx** [comment]
In testing this PR in Windows Powershell, it produces:
`Extension error:
Could not import extension sphinx_tabs.tabs (exception: No module named 'sphinx_tabs')`

In contrast, when I build this PR and test it in WSL, it builds fine. Is there a difference in the command syntax, or something that you installed or configured in PowerShell? I used the normal: `.\make.bat html`

I rarely use Powershell to build the docs. I found this error odd. Hoping you can shed light on this.

**Comment by mvincerx** [comment]
@mvincerx Please review again.

**Comment by intelkevinputnam** [comment]
It looks like the error results from the sphinx-tabs library not being installed. Try running "pip install sphinx-tabs" and then try building again.

**Comment by mvincerx** [comment]
Yes, thanks, will do.

**Comment by mvincerx** [comment]
Oh dear. I apologize, I made a tiny syntax error when running the make bat command. 
Sphinx tabs were already installed--sanity restored---so the error I produced was actually a red herring. It had nothing to do with sphinx-tabs. Sorry for the delay.

**Comment by mvincerx** [comment]
LGTM.

**Pull request merged**
