### PR TITLE
Add a ZFS tutorial

### PR DESCRIPTION
**Pull request by peteonrails**
This PR introduces a new tutorial for ZFS. I have read the contribution guidelines and have tried to adhere to them -- feedback welcome.

I stopped before adding a ZFS-on-root section because this tutorial is already long. ZFS-on-root is substantially harder, so I would welcome feedback about whether it should be a section of this tutorial, or a tutorial all of its own. 

I hope this PR will help the many users who ask the core team weekly about adding a ZFS driver to Clear Linux. For that reason, the background section is a little bit longer than most of the other sections. I could see a case for trimming that content, but I think it helpful to reduce questions int he future. 

I've contributed to open source projects before, so I expect to run a gauntlet of feedback here. 

Thanks in advance for considering this request.

### CODE REVIEW

**Comment by peteonrails** [comment]
Failing check is "Resource not accessible by integration" in the greetings check. I'm not sure this changeset caused that problem.

**Comment by mvincerx** [comment]
> Failing check is "Resource not accessible by integration" in the greetings check. I'm not sure this changeset caused that problem.
Thanks for the contribution, @peteonrails. Here are a few housekeeping details.  
* Yes, failure of the `greetings` has nothing to do with your PR. Ignore it. 
* Please create a `branch` from your existing `master` and resubmit a new PR.
See: https://docs.01.org/clearlinux/latest/collaboration/collaboration.html#contribute-via-github
* We'll review your re-submitted PR this week. 

If you belong to a Clear Linux mailing list, please let us know which one.  If you are a member on the forum, will you please indicate your username? Thanks in advance.

**Comment by peteonrails** [comment]
Closed in favor of https://github.com/clearlinux/clear-linux-documentation/pull/1174

**Comment by peteonrails** [comment]
> > Failing check is "Resource not accessible by integration" in the greetings check. I'm not sure this changeset caused that problem.
> > Thanks for the contribution, @peteonrails. Here are a few housekeeping details.
> 
>     * Yes, failure of the `greetings` has nothing to do with your PR. Ignore it.
> 
>     * Please create a `branch` from your existing `master` and resubmit a new PR.
>       See: https://docs.01.org/clearlinux/latest/collaboration/collaboration.html#contribute-via-github
> 
>     * We'll review your re-submitted PR this week.
> 
> 
> If you belong to a Clear Linux mailing list, please let us know which one. If you are a member on the forum, will you please indicate your username? Thanks in advance.

Thank you for the fast feedback. I have opened a PR from a branch and added contact info there. Much appreciated.

**Pull request closed without merging**
