### PR TITLE
dlrs tutorial update

### PR DESCRIPTION
**Pull request by bd-dean**
Please don't merge until docker hub links are verified.

### CODE REVIEW

**Comment by mvincerx** [comment]
@bd-dean See my latest commit.

**Comment by mvincerx** [comment]
@bd-dean. I resolved minor merge conflict. Please see my [last commit](https://github.com/clearlinux/clear-linux-documentation/pull/410/commits/acbe32f9f54970d981ba9993062f809f499efece)

**Comment by mvincerx** [comment]
LGTM. @bd-dean: Awaiting your approval of my edits.

**Comment by bd-dean** [comment]
@mvincerx Looks great & I approve.  Thank you!

**Pull request merged**
