### PR TITLE
Change the lts version of kernel for virtual box

### PR DESCRIPTION
**Pull request by abecastillo**
Updating virtual box installation document to reflect latest LTS
kernel version (4.14) released on Nov 2017.

### CODE REVIEW

**Comment by tpleavitt** [comment]
Other issues I've found in this file:

On line 76, change:      c. Version: **Linux 2.6 / 3.x / 4.x (64-bit)**  -to-     b. Version: **Linux 2.6 / 3.x / 4.x (64-bit)**
On line 103:  You reference kernel 4.9, do you want to change this to 4.14 as well?

On line 139:  change "use always" to "always use"

**Comment by abecastillo** [comment]
v2 patch submitted with proposed changes.

**Comment by abecastillo** [comment]
Thank you Mike!

On May 24, 2018 4:14 PM, mltullis <notifications@github.com> wrote:

Merged #147<https://github.com/clearlinux/clear-linux-documentation/pull/147>.

**Comment by mltullis** [comment]
@abecastillo   Sure, thanks for the contribution. This should go live in today's auto-build.

**Comment by mvincerx** [comment]
Yes, thank you very much, Mike.

**Pull request merged**
