### PR TITLE
 Add document on installing proprietary NVIDIA drivers

### PR DESCRIPTION
**Pull request by puneetse**
Combined with https://github.com/clearlinux/clear-linux-documentation/pull/424, this PR closes https://github.com/clearlinux/clear-linux-documentation/issues/369 

This PR:

- Adds a new document on installing proprietary NVIDIA drivers
- Adds the new document to the tutorials TOC tree 
- Adds include points in the kernel-modules-dkms documents which are used in the new document

### CODE REVIEW

**Comment by mvincerx** [comment]
@puneetse. I'll provide more feedback Tues on validation. Otherwise, this PR builds fine; you can ignore two errors that occur if building this locally.  Errors are being addressed in another PR or already merged.

**Comment by puneetse** [comment]
https://github.com/clearlinux/distribution/issues/324

**Comment by puneetse** [comment]
@mvincerx no problem, thanks for the update.

**Comment by mvincerx** [comment]
LGTM. FYI: Minor build errors will be resolved on merge because upstream master is ahead of your branch.

**Pull request merged**
