### PR TITLE
Update TM&B in About section of docs

### PR DESCRIPTION
**Pull request by krisdale**
- Add disclaimers for Intel trademarks
- Add asterisk for 3rd party trademarks
- Remove redundant asterisks (only first use needed)

Signed-off-by: Kristal Dale <kristal.dale@intel.com>

### CODE REVIEW

**Comment by krisdale** [comment]
In the last table - the networks entry - "NetworkManager by default*" What is the asterisk on 'default' trying to convey?

**Comment by mvincerx** [comment]
> In the last table - the networks entry - "NetworkManager by default*" What is the asterisk on 'default' trying to convey?

Please remove the asterisk after `default`.

**Comment by mvincerx** [comment]
Please hold on this, @krisdale. I'll push to make a tiny correction re your question above.

**Comment by mvincerx** [comment]
> In the last table - the networks entry - "NetworkManager by default*" What is the asterisk on 'default' trying to convey?

Good catch.  I removed * and added a "See note below..." to make the connection to legacy networking on CL.

**Comment by mvincerx** [comment]
LGTM.

**Pull request merged**
