### PR TITLE
Rebuilds bundle.html manually combining two scripts:

### PR DESCRIPTION
**Pull request by mvincerx**
- http://kojiclear.jf.intel.com/cgit/projects/bundle-tools¸ ./gendocs.sh
- script provided by matthew johnson, https://github.com/clearlinux/clear-linux-documentation/issues/126

Signed-off-by: Michael Vincerra <michaelx.vincerra@intel.com>

### CODE REVIEW

**Comment by mvincerx** [comment]
Please see my latest push that captures your most recent requests above.

**Comment by tpleavitt** [comment]
Would you put this in the temp build so I can look at it?

**Comment by tpleavitt** [comment]
Never mind.  I'll look at the live version when it is published

**Comment by mltullis** [comment]
No prob. You can see the staging build here. I just ran Jenkins:
https://stg.clearlinux.org/documentation/clear-linux/reference/bundles/available-bundles 
Be sure to dump your cache.

**Comment by mvincerx** [comment]
@tpleavitt, OK. Great. (Saved me an email, thanks.) If you have any further issues, just let me know.

**Pull request merged**
