### PR TITLE
Adds program-generated bundle and packages list referenced in bundles.rst

### PR DESCRIPTION
**Pull request by mvincerx**

### CODE REVIEW

**Comment by mvincerx** [comment]
@mltullis review optional. @intelkevinputnam can you please also review use of new `.txt` file extension? That file rendered fine for me with directive `:raw:` set as `html`.

**Comment by mvincerx** [comment]
OK.  A little funny, how? 
I know it may look like the time and date stamp "float" at upper right, but they're included in table.

**Comment by intelkevinputnam** [comment]
Maybe, but it still looks out of place in the read the docs theme. 

image

**Comment by mvincerx** [comment]
@intelkevinputnam. Please see latest commit.

**Pull request merged**
