### PR TITLE
Adds :contents: directive to Clear Linux collaboration guide.

### PR DESCRIPTION
**Pull request by mvincerx**
Signed-off-by: Michael Vincerra <michael.vincerra@intel.com>

### CODE REVIEW

**Comment by mvincerx** [comment]
@intelkevinputnam 
I'm hoping that you can review this and back me up. Presently, I'm working on Sublime freeware until official version arrives. Please render and let me know if you find any anomalies.

**Comment by intelkevinputnam** [comment]
Looks like this as of now:

image

**Comment by mvincerx** [comment]
Thanks. I see what I need to fix now.

**Comment by mvincerx** [comment]
@intelkevinputnam. Please check the rendering when time. Correction applied shows TOC in document.

**Pull request merged**
