### PR TITLE
Revise and simplify swupd-about.

### LINKED ISSUE #399: Odd arguments about package management with other distros
Following document: https://clearlinux.org/documentation/clear-linux/concepts/swupd-about

Has odd arguments about  package management "issues" with other distributions (i.e. what advantages swupd / bundles would have compared to them):

* "This can be done effectively, but given the nearly endless combinations of packages and versions of packages a server may have, it quickly becomes non-trivial to define what “version” the system is and what software it is running without explicitly going through each system and inspecting every package."

* "This matters on a daily basis to system administrators, who need to determine which of their systems do not have the latest security fixes, or which combinations of software have been tested."

For example, on Debian / Ubuntu:

* Checking whether available security updates have been installed, can be seen with "apt update" command (which is shorter command than "swupd check-update")

* If maintainer just wants everything to have the latest security updates, s/he just enables automatic security updates

* If s/he wants more control, machines s/he maintains get packages from a mirror / proxy in her/his control (which is updated from upstream only after testing, or where packages are "hand-picked")

So basically the "advantages" boil into swupd providing a single number for identifying the distribution package content.  However, that's not really useful as it doesn't tell anything.

As far as I can see, there's no way in ClearLinux to find out relevant things corresponding to its distro version:
* Does it have version of Y (or newer) of package B, which got the feature my app would need?
* Does it include version X of package A with a known security vulnerability?
* Does it have patch applied that fixes the issue?

E.g. in Debian/Ubuntu:
* "dpkg -s <package>" shows the package upstream version
* "apt source <package>" fetches package sources for more in-depth examination
* there's also a www-site where one can check which package versions are in which distro versions, their changelogs, included files, applied changes and a list of package specific bugs:
 ** https://packages.ubuntu.com/
 ** https://packages.debian.org/

### PR DESCRIPTION
**Pull request by mvincerx**
- Closes #399
- Limit description to swupd functionality and contrasts

Signed-off-by: Michael Vincerra <michael.vincerra@intel.com>

### CODE REVIEW

**Comment by mvincerx** [comment]
Saludos! @otaviobp, please review as we discussed.

**Comment by mvincerx** [comment]
Thanks for your review @otaviobp.

**Comment by mvincerx** [comment]
@puneetse, thoughts?

**Comment by mvincerx** [comment]
@puneetse. I'd like this merged by Wed. at noon. Could you provide feedback/additions by then? 
If not, you could always open another PR and suggest changes.

**Comment by puneetse** [comment]
@mvincerx See my take on this here:

[edit/ps-swupd-about](https://github.com/puneetse/clear-linux-documentation/blob/edit/ps-swupd-about/source/clear-linux/concepts/swupd-about.rst) or here [compare mvincerx:mv-swupd-about and  puneetse:edit/ps-swupd-about](https://github.com/mvincerx/clear-linux-documentation/compare/mv-swupd-about...puneetse:edit%2Fps-swupd-about?diff=split&expand=1) 

Basically, I'd like to renew the focus of this document on swupd, how it operates, and how it influences CL. Right now the document focuses too much on bundles (in fact, even in my take I think the bundle section may be too much - there are other docs for that) and negatively comparing with other distros. 

Let me know what you think and how you want to proceed. If you agree, I can update your branch or submit a new PR.

**Comment by mvincerx** [comment]
@puneetse.  I think it may work best if you approve this now. Then, you can submit a new PR. 

First, let me put this in perspective. This version of `swupd-about` may have a shelf-life of 3-4 months.  I don't want anyone to spend too much effort refining this because [...] "perfect is the enemy of the good," and ultimately the content of this page will be summarized further. 
Second, I'd like this document to be its current length--or even shorter. Third, I'd like to know more about what you mean by "how [swupd] influences CL." I struggled with shortening the previous draft, and I considered removing bundles altogether. However, I think at least 1 para. should be dedicated to explaining how swupd is used for bundle/package installation and maintenance.  Thoughts?

**Comment by mvincerx** [comment]
@puneetse. Also, if you find any inaccuracies in this draft, please suggest edits.

**Comment by puneetse** [comment]
> @puneetse. I think it may work best if you approve this now. Then, you can submit a new PR.

Sounds good!

> This version of `swupd-about` may have a shelf-life of 3-4 months.
I understand but the content is still going to be reused.

**Comment by mvincerx** [comment]
Yes. Reuse, recycle... rock on! Thanks @puneetse

**Pull request merged**
