### PR TITLE
Remove UEFI requirement per clr-installer release.

### LINKED ISSUE #1207: UEFI isn't already mandatory but documentation still states it is
According to this already fixed and closed issue of Clear Linux installer:
https://github.com/clearlinux/clr-installer/issues/517
and this already merged and closed pull request, related to that issue:
https://github.com/clearlinux/clr-installer/pull/666
Clear Linux already supports installation on computers without UEFI enabled.

However the official Clear Linux documentation of system requirements still states that
the UEFI support in the computer is mandatory:
https://docs.01.org/clearlinux/latest/reference/system-requirements.html
> and it requires a system that supports UEFI

Also the official instructions of how to configure a dual-boot of Clear Linux and Windows
don't support computers without UEFI:
https://docs.01.org/clearlinux/latest/tutorials/multi-boot/dual-boot-win.html

Also I can't find what boot loader is used on such computers.
Commit message of the merged commit mention a URL to Syslinux:
https://github.com/mdhorn/clr-installer/commit/294d767c2146b145a191b704d2b067c26dd7bcd5
Is it Syslinux? A good chose, IMO. I personally don't like Grub2.

Please fix the system requirements, the dual-boot configuration instructions and probably
other documentation about boot.

### PR DESCRIPTION
**Pull request by mvincerx**
- https://github.com/clearlinux/clr-installer/pull/666
- Closes #1207

Signed-off-by: michael vincerra <michael.vincerra@intel.com>

### CODE REVIEW

**Comment by rosti-il** [comment]
Seems good to me, although it could be much better to add a clear statement that both computer configurations (with and without UEFI) are supported.

Also my #1207 bug report asks to document the boot manager (Syslinux ?) that is used when UEFI is disabled or unavailable. It might be enough to document how to configure dual boot of Clear Case and Windows using that boot manager, in addition to the existing documentation about how to do that using UEFI:
https://docs.01.org/clearlinux/latest/tutorials/multi-boot/dual-boot-win.html

Please document it by another commit in this PR or don't close #1207 when this PR is merged.

**Comment by mdhorn** [comment]
@rosti-il The default boot loader will depend on how you partition the media and the file system used; see the [clr-boot-manager readme](https://github.com/clearlinux/clr-boot-manager#supported-filesystemspartition-table).
@mvincerx I don't like repeating information in multiple places as it makes updates like these complex -- if you want, you can add a reference to the clr-boot-manager's readme for details on the default boot loader as it is the application responsible for setting it up.

**Review by mdhorn — APPROVED** [review]
This is fine by me as-is, but if you want to add something about the default boot loader used, reference the clr-boot-manager's readme.

**Comment by mvincerx** [comment]
Thanks @mdhorn

**Pull request merged**
