### PR TITLE
Issue #314 Add Alternative to Multiboot to Chain Grub

### PR DESCRIPTION
**Pull request by linjiach**
Tested with Clear + Ubuntu 18.04 LST

https://github.com/clearlinux/clear-linux-documentation/issues/314

Signed-off-by: Linjia Chang

### CODE REVIEW

**Comment by mvincerx** [comment]
FYI: I will test the multi-boot Ubuntu 18.04 use case .

**Comment by intelkevinputnam** [comment]
I'll test the multi-boot Mint usecase.

**Comment by intelkevinputnam** [comment]
If the intent is to enable side-by-side booting of both Mint and Clear Linux from the GRUB boot menu then the tutorial is insufficient. As written, it is not possible to boot into Clear Linux, as the Clear Linux boot option isn't added to the GRUB  boot list. Unless, I missed something, that is.

**Comment by mvincerx** [comment]
Per Clear Linux docs meeting, the multi-boot document will be refactored to include only scenarios with Ubuntu, Fedora, and Windows 10; therefore, this PR will be closed (some content here to be used in new PR). Reference CLEAR-3987.

**Pull request closed without merging**
