### PR TITLE
Update available bundles 05-14-19. Revise intro, bundles.rst.

### PR DESCRIPTION
**Pull request by mvincerx**
Signed-off-by: Michael Vincerra <michael.vincerra@intel.com>

### CODE REVIEW

**Comment by mvincerx** [comment]
Enjoy the branch name typo.  Need this reviewed asap, please.

**Comment by intelkevinputnam** [comment]
In Progress

**Comment by intelkevinputnam** [comment]
Other than small change to wording to remove referencing "column one" it looks good.

**Comment by mvincerx** [comment]
@intelkevinputnam. Thanks a bunch for the quick turnaround.

**Pull request merged**
